(: /escrutinio_sitio/num_a_elegir :)
(: /escrutinio_sitio/resultados/partido[votos_numero>20000]/nombre :)
(: /escrutinio_sitio/resultados/partido[votos_porciento = max(/escrutinio_sitio/resultados/partido/votos_porciento)]/nombre :)
(: /escrutinio_sitio/resultados/partido[nombre = "PSOE"]/electos :)
 (: /escrutinio_sitio/porciento_escrutado :)
 (: /escrutinio_sitio/votos/nulos/porcentaje :)
(: count(/escrutinio_sitio/resultados/partido[electos>0]) :)
(: /escrutinio_sitio/votos/contabilizados/cantidad :)
(: count(/escrutinio_sitio/resultados/partido[electos=0]) :)
(: /escrutinio_sitio/resultados/partido[nombre="Cs"]/electos :)
(: count(/escrutinio_sitio/resultados/partido[votos_numero < 1000]) :)
(: data(/escrutinio_sitio/resultados/partido[electos=0]/nombre) :)
(: /escrutinio_sitio/resultados/partido[nombre="PODEMOS-EQUO"]/id_partido :)
(: (/escrutinio_sitio/resultados/partido)[1] :)
(: /escrutinio_sitio/convocatoria :)
(: /escrutinio_sitio/resultados/partido[votos_numero = max(/escrutinio_sitio/resultados/partido/votos_numero)]/nombre :)
(: /escrutinio_sitio/resultados/partido[nombre = "VOX"]/votos_numero :)
(: /escrutinio_sitio/resultados/partido[electos = min(/escrutinio_sitio/resultados/partido/electos)]/nombre :)
(: /escrutinio_sitio/resultados/partido[votos_porciento = 0]/nombre :)
/escrutinio_sitio/resultados/partido[last()]